# Generated by Django 4.2.4 on 2023-08-03 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('background_image', models.ImageField(upload_to='hackathons/backgrounds/')),
                ('hackathon_image', models.ImageField(upload_to='hackathons/images/')),
                ('type_of_submission', models.CharField(choices=[('image', 'Image'), ('file', 'File'), ('link', 'Link')], max_length=10)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reward_prize', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hackathons_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_name', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('image_submission', models.ImageField(blank=True, null=True, upload_to='submissions/images/')),
                ('file_submission', models.FileField(blank=True, null=True, upload_to='submissions/files/')),
                ('link_submission', models.URLField(blank=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.hackathon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
